export const roles = {
  1: 'Base',
  2: 'Fly',
  3: 'Spot',
  4: 'Longe',
}

export const tasks = [
  // Basic tasks (no specific action)
  { text: 'Complete your nakki (voluntary task)', difficulty: 5 },
  { text: 'Pump fists with Perttu', difficulty: 1 },
  { text: 'High five Hattu', difficulty: 1 },
  { action: 'move', text: 'Fly with Jukka basing', difficulty: 1, role: 2 },
  { text: 'Hug Shingo', difficulty: 2 },
  { text: 'Group acro in group of 4', difficulty: 2 },
  { text: 'Do acroyoga washing machine', difficulty: 2 },
  { text: 'Introduce yourself to a new person', difficulty: 1 },
  { text: 'Flyer basing, base flying', difficulty: 2 },
  // { text: "All upside down", difficulty: 2 },
  { text: 'Handstand how ever', difficulty: 2 },
  { text: 'Headstand how ever', difficulty: 2 },
  { text: 'Do a pyramid', difficulty: 2 },
  { text: 'Wait in line for microwave', difficulty: 1 },
  { text: 'Learn new trick', difficulty: 2 },
  { text: 'Walk to the cheer gym', difficulty: 1 },
  { text: 'Look for a chalk bottle', difficulty: 1 },
  { text: 'Drink a hydration drink', difficulty: 1 },
  { text: 'Take a photo/video', difficulty: 1 },
  { text: 'Post something on instagram tag @finn.acro', difficulty: 2 },
  { text: 'Take a power nap', difficulty: 1 },
  { text: 'Do a trick on the trampoline', difficulty: 2 },
  { text: 'Juggle', difficulty: 2 },
  { text: 'Brew coffee', difficulty: 2 },
  { text: 'Clean something, even if it\'s not your responsibility', difficulty: 2 },
  { text: 'participate in free training', difficulty: 1 },
  { text: 'Give someone a short massage', difficulty: 1 },
  { text: 'Pull lines for someone', difficulty: 2 },
  { text: 'Do parkour', difficulty: 2 },
  { text: 'Balance on gymball', difficulty: 2 },
  { text: 'Hulahoop in acro pose', difficulty: 2 },
  { text: 'Jump on the trampoline', difficulty: 1 },
  { text: 'Lie on the couch', difficulty: 1 },
  { text: 'Jump with a jumprope', difficulty: 1 },
  { text: 'Warmup using a resistance band', difficulty: 1 },
  { text: 'Belly base something', difficulty: 1 },
  { text: 'Base something on knees', difficulty: 1 },
  { text: 'L-base: two bases one flyer', difficulty: 1 },
  { text: 'Play rock paper scissors until you beat 3 people', difficulty: 1 },
  { text: 'Complement someone', difficulty: 1 },

  // Say actions
  { action: 'say', text: 'One more', difficulty: 1 },
  { text: 'Don\'t say "one more" for a whole workshop', difficulty: 2 },
  { action: 'say', text: 'I\'d love to spot for you', difficulty: 1 },
  { action: 'say', text: 'Can you spot for us', difficulty: 1 },
  { action: 'say', text: 'Use your legs/use more legs/more legs', difficulty: 1 },
  { action: 'say', text: 'Do less', difficulty: 1 },
  { action: 'say', text: 'Do slower', difficulty: 1 },
  { action: 'say', text: 'Let\'s try something silly', difficulty: 1 },
  { action: 'say', text: 'Squat/squat more', difficulty: 1 },
  { action: 'say', text: 'Happy new year', difficulty: 1 },
  { action: 'say', text: 'Can you take a photo/video', difficulty: 1 },
  { action: 'say', text: 'How would you like to come down?', difficulty: 1 },
  { action: 'say', text: 'Would you like a spotter?', difficulty: 1 },
  { action: 'say', text: 'This might hurt a little bit', difficulty: 1 },
  { action: 'say', text: 'This is gonna hurt, but I\'m gonna do it anyway', difficulty: 1 },
  { action: 'say', text: 'Wait', difficulty: 1 },
  { action: 'say', text: 'Enjoy the ride', difficulty: 1 },
  { action: 'say', text: 'Faster', difficulty: 1 },
  { action: 'say', text: 'Faster hands', difficulty: 1 },
  { action: 'say', text: 'Do more', difficulty: 1 },
  { action: 'say', text: 'Let the base to their job', difficulty: 1 },
  { action: 'say', text: 'The other left/right', difficulty: 1 },

  // Move actions (with roles)
  { action: 'move', text: 'f2h', difficulty: 2, role: 1 },
  { action: 'move', text: 'f2h', difficulty: 2, role: 2 },
  { action: 'move', text: 'f2h', difficulty: 2, role: 3 },
  { action: 'move', text: 'f2h', difficulty: 2, role: 4 },

  { action: 'move', text: 'h2h', difficulty: 3, role: 1 },
  { action: 'move', text: 'h2h', difficulty: 3, role: 2 },
  { action: 'move', text: 'h2h', difficulty: 3, role: 3 },
  { action: 'move', text: 'h2h', difficulty: 3, role: 4 },

  { action: 'move', text: 'bird', difficulty: 1, role: 1 },
  { action: 'move', text: 'bird', difficulty: 1, role: 2 },
  { action: 'move', text: 'bird', difficulty: 1, role: 3 },
  { action: 'move', text: 'bird', difficulty: 1, role: 4 },

  { action: 'move', text: 'sidestar', difficulty: 2, role: 1 },
  { action: 'move', text: 'sidestar', difficulty: 2, role: 2 },
  { action: 'move', text: 'sidestar', difficulty: 1, role: 3 },
  { action: 'move', text: 'sidestar', difficulty: 2, role: 4 },

  { action: 'move', text: '2mh', difficulty: 2, role: 1 },
  { action: 'move', text: '2mh', difficulty: 2, role: 2 },
  { action: 'move', text: '2mh', difficulty: 1, role: 3 },
  { action: 'move', text: '2mh', difficulty: 2, role: 4 },

  { action: 'move', text: '3mh', difficulty: 4, role: 1 },
  { action: 'move', text: '3mh', difficulty: 4, role: 2 },
  { action: 'move', text: 'mid 3mh', difficulty: 4, role: 1 },
  { action: 'move', text: 'mid 3mh', difficulty: 4, role: 2 },
  { action: 'move', text: '3mh', difficulty: 2, role: 3 },
  { action: 'move', text: '3mh', difficulty: 3, role: 4 },

  { action: 'move', text: 'try something silly', difficulty: 2, role: 1 },
  { action: 'move', text: 'try something silly', difficulty: 2, role: 2 },
  { action: 'move', text: 'try something silly', difficulty: 1, role: 3 },
  { action: 'move', text: 'try something silly', difficulty: 2, role: 4 },

  { action: 'move', text: 'take a trick/move out of lines', difficulty: 2, role: 1 },
  { action: 'move', text: 'take a trick/move out of lines', difficulty: 2, role: 2 },
  { action: 'move', text: 'take a trick/move out of lines', difficulty: 1, role: 3 },
  { action: 'move', text: 'take a trick/move out of lines', difficulty: 2, role: 4 },

  { action: 'move', text: 'backbird', difficulty: 2, role: 1 },
  { action: 'move', text: 'backbird', difficulty: 2, role: 2 },
  { action: 'move', text: 'backbird', difficulty: 1, role: 3 },
  { action: 'move', text: 'backbird', difficulty: 2, role: 4 },

  { action: 'move', text: 'shoulderstand', difficulty: 1, role: 1 },
  { action: 'move', text: 'shoulderstand', difficulty: 1, role: 2 },
  { action: 'move', text: 'shoulderstand', difficulty: 1, role: 3 },
  { action: 'move', text: 'shoulderstand', difficulty: 2, role: 4 },

  { action: 'move', text: 'something hands free', difficulty: 2, role: 1 },
  { action: 'move', text: 'something hands free', difficulty: 2, role: 2 },
  { action: 'move', text: 'something hands free', difficulty: 1, role: 3 },
  { action: 'move', text: 'something hands free', difficulty: 2, role: 4 },

  { action: 'move', text: 'croc', difficulty: 2, role: 1 },
  { action: 'move', text: 'croc', difficulty: 2, role: 2 },
  { action: 'move', text: 'croc', difficulty: 1, role: 3 },
  { action: 'move', text: 'croc', difficulty: 2, role: 4 },

  { action: 'move', text: 'a trick/move with a teacher', difficulty: 2, role: 1 },
  { action: 'move', text: 'a trick/move with a teacher', difficulty: 2, role: 2 },
  { action: 'move', text: 'a trick/move for a teacher', difficulty: 1, role: 3 },
  { action: 'move', text: 'a trick/move for a teacher', difficulty: 2, role: 4 },

  { action: 'move', text: 'pitch', difficulty: 2, role: 1 },
  { action: 'move', text: 'pitch', difficulty: 2, role: 2 },
  { action: 'move', text: 'pitch', difficulty: 1, role: 3 },
  { action: 'move', text: 'pitch', difficulty: 2, role: 4 },

  { action: 'move', text: 'banquine', difficulty: 2, role: 1 },
  { action: 'move', text: 'banquine', difficulty: 2, role: 2 },
  { action: 'move', text: 'banquine', difficulty: 2, role: 3 },
  { action: 'move', text: 'banquine', difficulty: 2, role: 4 },

  { action: 'move', text: 'swing', difficulty: 2, role: 1 },
  { action: 'move', text: 'swing', difficulty: 2, role: 2 },
  { action: 'move', text: 'swing', difficulty: 2, role: 3 },
  { action: 'move', text: 'swing', difficulty: 2, role: 4 },

  { action: 'move', text: 'counterbalance', difficulty: 2, role: 1 },
  { action: 'move', text: 'counterbalance', difficulty: 2, role: 2 },
  { action: 'move', text: 'counterbalance', difficulty: 2, role: 3 },
  { action: 'move', text: 'counterbalance', difficulty: 2, role: 4 },

  { action: 'move', text: 'throne', difficulty: 1, role: 1 },
  { action: 'move', text: 'throne', difficulty: 1, role: 2 },
  { action: 'move', text: 'throne', difficulty: 1, role: 3 },
  { action: 'move', text: 'throne', difficulty: 2, role: 4 },

  { action: 'move', text: 'camel', difficulty: 1, role: 1 },
  { action: 'move', text: 'camel', difficulty: 1, role: 2 },
  { action: 'move', text: 'camel', difficulty: 1, role: 3 },
  { action: 'move', text: 'camel', difficulty: 2, role: 4 },

  { action: 'move', text: 'f2f', difficulty: 2, role: 1 },
  { action: 'move', text: 'f2f', difficulty: 2, role: 2 },
  { action: 'move', text: 'f2f', difficulty: 1, role: 3 },
  { action: 'move', text: 'f2f', difficulty: 2, role: 4 },

  { action: 'move', text: 'icarian', difficulty: 2, role: 1 },
  { action: 'move', text: 'icarian', difficulty: 2, role: 2 },
  { action: 'move', text: 'icarian', difficulty: 2, role: 3 },
  { action: 'move', text: 'icarian', difficulty: 3, role: 4 },
]
