/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/2022/': RouteRecordInfo<'/2022/', '/2022', Record<never, never>, Record<never, never>>,
    '/2023-ny-en/': RouteRecordInfo<'/2023-ny-en/', '/2023-ny-en', Record<never, never>, Record<never, never>>,
    '/2023-ny-fi/': RouteRecordInfo<'/2023-ny-fi/', '/2023-ny-fi', Record<never, never>, Record<never, never>>,
    '/2023-summer/': RouteRecordInfo<'/2023-summer/', '/2023-summer', Record<never, never>, Record<never, never>>,
    '/2024-ny-en/': RouteRecordInfo<'/2024-ny-en/', '/2024-ny-en', Record<never, never>, Record<never, never>>,
    '/2024-ny-fi/': RouteRecordInfo<'/2024-ny-fi/', '/2024-ny-fi', Record<never, never>, Record<never, never>>,
    '/2024-summer-en/': RouteRecordInfo<'/2024-summer-en/', '/2024-summer-en', Record<never, never>, Record<never, never>>,
    '/2024-summer-fi/': RouteRecordInfo<'/2024-summer-fi/', '/2024-summer-fi', Record<never, never>, Record<never, never>>,
    '/2025-summer-en/': RouteRecordInfo<'/2025-summer-en/', '/2025-summer-en', Record<never, never>, Record<never, never>>,
    '/2025-summer-fi/': RouteRecordInfo<'/2025-summer-fi/', '/2025-summer-fi', Record<never, never>, Record<never, never>>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/bingo': RouteRecordInfo<'/bingo', '/bingo', Record<never, never>, Record<never, never>>,
    '/en/': RouteRecordInfo<'/en/', '/en', Record<never, never>, Record<never, never>>,
    '/ennakko': RouteRecordInfo<'/ennakko', '/ennakko', Record<never, never>, Record<never, never>>,
    '/fa-admin': RouteRecordInfo<'/fa-admin', '/fa-admin', Record<never, never>, Record<never, never>>,
    '/feedback': RouteRecordInfo<'/feedback', '/feedback', Record<never, never>, Record<never, never>>,
    '/fi/': RouteRecordInfo<'/fi/', '/fi', Record<never, never>, Record<never, never>>,
    '/ilmoittaudu': RouteRecordInfo<'/ilmoittaudu', '/ilmoittaudu', Record<never, never>, Record<never, never>>,
    '/info/': RouteRecordInfo<'/info/', '/info', Record<never, never>, Record<never, never>>,
    '/jam': RouteRecordInfo<'/jam', '/jam', Record<never, never>, Record<never, never>>,
    '/live': RouteRecordInfo<'/live', '/live', Record<never, never>, Record<never, never>>,
    '/palaute': RouteRecordInfo<'/palaute', '/palaute', Record<never, never>, Record<never, never>>,
    '/README': RouteRecordInfo<'/README', '/README', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/s': RouteRecordInfo<'/s', '/s', Record<never, never>, Record<never, never>>,
    '/signup': RouteRecordInfo<'/signup', '/signup', Record<never, never>, Record<never, never>>,
    '/teacher-info': RouteRecordInfo<'/teacher-info', '/teacher-info', Record<never, never>, Record<never, never>>,
    '/timetable': RouteRecordInfo<'/timetable', '/timetable', Record<never, never>, Record<never, never>>,
  }
}
